### ISSUE TITLE
Enable keycloak authentication for ui

### ISSUE THREAD

**Issue by dicolasi** [Apicurio/apicurio-registry-operator#105]
Ho do I pass the keycloak parameters to enable authentication? I can't see those in the CRD.

**Comment by dicolasi** [comment]
This is linked to this question -> https://github.com/Apicurio/apicurio-registry/issues/1093

**Comment by andrew-musoke** [comment]
+1 Has this been worked on? Am trying to use this solution for Kafka schema registry and would like some sort of auth wall

**Comment by EricWittmann** [comment]
This is being worked on now as part of the operator changes to support Apicurio Registry 2.0 (which should have a release candidate build done this week).
