### ISSUE TITLE
User interface error (Error searching for artifacts)

### ISSUE THREAD

**Issue by andrew-musoke** [Apicurio/apicurio-registry-operator#117]
Hi. 
I successfully deployed the operator and registry CR. Both pods are working fine without any errors in the logs, even in debug mode.

Accessing the UI takes about 5 minutes to load and then shows this error

```
{
   "message": "Network Error",
   "name": "Error",
   "stack": "Error: Network Error\n    at e.exports (https://schema-registry-dev.domain.com/ui/vendors.bundle.6b1a271b69192f98d9e5.js:289:56022)\n    at XMLHttpRequest.h.onerror 

- (https://schema-registry-dev.domain.com/ui/vendors.bundle.6b1a271b69192f98d9e5.js:80:46039)",

   "config": {
      "url": "http://schema-registry-dev.domain.com/api/search/artifacts?limit=10&order=asc&over=everything",
      "method": "get",
      "headers": {
         "Accept": "application/json"
      },
      "transformRequest": [
         null
      ],
      "transformResponse": [
         null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1
   }
}
```

Here is the network waterfall incase it helps: 
![image](https://user-images.githubusercontent.com/25344830/109341048-82250080-7872-11eb-84e5-8c3392d93347.png)

It also appears that some resources are fetched over http yet the original request was in https not sure why
![image](https://user-images.githubusercontent.com/25344830/109341917-c664d080-7873-11eb-9042-4e7312cd0f70.png)

Versions are:
- Google Chrome browser 
`Version 88.0.4324.182 (Official Build) (64-bit)`
- Kubernetes 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Operator 
`0.0.4`
- Registry CR
`1.3.2.Final`

**Comment by andrew-musoke** [comment]
Update...
I am using Istio for my traffic ingress. The gateway I used for my domain was set to automatically redirect http traffic to https. So when I accessed on https, I got the error above. 

I turned this off and accessed the UI over http and the error disappeared. 

I will not close the issue because http is clearly not the ideal choice for the UI traffic and would love a fix.

**Comment by andrew-musoke** [comment]
Update...
This was related to [#513](https://github.com/Apicurio/apicurio-registry/issues/513). Fixed it for Istio using [this](https://github.com/Apicurio/apicurio-registry/issues/513#issuecomment-787504674).

**Comment by EricWittmann** [comment]
@jsenko and @smccarthy-ie should this be added to documentation?

**Comment by jsenko** [comment]
I would err on the side of having this documented rather than not. Created #118 to keep track.
