### ISSUE TITLE
Support for volume configurations

### ISSUE THREAD

**Issue by JJJJJones** [Apicurio/apicurio-registry-operator#120]
With [k8s 1.20 removing PodPresets](https://kubernetes.io/docs/setup/release/notes/#deprecation) we no longer have a way to add volume's externally to apicurio-registry-operator's configuration so we'd like to extend the operator with support for that feature.

I'm working on a PR for this feature request.

**Comment by jsenko** [comment]
Hi @JJJJJones Could you please help me understand better your use case? Why do you need to attach volumes to the operator pod? I would help me review you PRs. Thanks!

**Comment by JJJJJones** [comment]
Hello @jsenko, more than happy to try and explain. It's advised to use ReadOnlyRootFilesystem to improve pod security but apicurio-registry needs R/W access to /tmp. To address this without disabling ReadOnlyRootFilesystem we've been adding an EmptyDir volume at /tmp of the apicurio-registry pods via a PodPreset. With PodPresets going away in k8s 1.20, we'll need the ability to add volumes to apicurio-registry pods through the operator instead. I hope this gives you a better understanding of what we're doing and why.

**Comment by jsenko** [comment]
PR merged. Thank you!
