### ISSUE TITLE
What is the operator doing?

### ISSUE THREAD

**Issue by estahn** [Apicurio/apicurio-registry-operator#128]
What is the operator doing that couldn't be done with a regular helm chart?

**Comment by jsenko** [comment]
Could you elaborate on your question please?

**Comment by estahn** [comment]
@jsenko Sure thing. I'm wondering why this requires an operator to function instead of using Kubernetes literals via Helm, kustomize, plain Manifest.

Does it need special consideration during balancing of some sorts or other things that are not available natively?

**Comment by jsenko** [comment]
The operator as-is could have probably been implemented using Helm, or similar simpler techniques. However, we plan some features in the future that may require full Operator Framework. That said, it was a decision by the developers, who did the work.
We're happy for any constructive criticism, but this does not seem to be very helpful.

**Comment by estahn** [comment]
@jsenko Apologies if this hit the wrong chord. I merely tried to understand the reasoning behind using a full-fledged operator.
