### ISSUE TITLE
Allow specifying pull secret for operands

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry-operator#145]
e.g. see https://github.com/strimzi/strimzi-kafka-operator/issues/773

**Comment by ajborley** [comment]
This has been implemented in PR #156 via a new `spec.deployment.imagePullSecrets` field in the CR, and a
REGISTRY_IMAGE_PULL_POLICY operator environment variable, allowing users to control how and when images are pulled. I think this issue can be closed.
