### ISSUE TITLE
Operator creating a registry which connects to a secured Kafka

### ISSUE THREAD

**Issue by sjwoodman** [Apicurio/apicurio-registry-operator#15]
As far as I can tell the Operator only supports creating registry instances which connect to a Kafka broker which has no security enabled. In production most Kafka brokers will have some kind of encryption, authentication and authorisation. For instance
* TLS encryption
* SASL authentication
* SCRAM-SHA-512 authentication

For example setups see: https://github.com/strimzi/strimzi-kafka-operator/tree/master/examples/security

**Comment by jsenko** [comment]
Resolved, a follow up issue is #32
