### ISSUE TITLE
[proposal] Add support for user-defined `podTemplate`

### ISSUE THREAD

**Issue by andreaTP** [Apicurio/apicurio-registry-operator#179]
**Problem**

The user wants to configure a "Kubernetes-specific" setting or add some "infrastructure" to the `Deployment` created by this operator to fit their own Kubernetes installation needs.
Common use cases are:

- add extra labels/annotations
- specify requests/limits
- mount extra volumes
- add a sidecar/init container
- specify tolerations
- etc...

Relevant open issues:
 - #80
 - #79

**Motivation**

It's hard to predict which "kubernetes features" will be used by users and it's extremely tedious and time-consuming to add them one by one.

**Proposal**

This proposal proposes a "catch-all" workaround to enable all of those cases removing the need for code changes and manual integration.
More specifically I'm here proposing to support the entire Kubernetes [`podTemplate`](https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates) to be merged on top of the `Deployment` currently generated by this operator.
`podTemplate` have been demonstrated flexible enough to support most of the users needs without the need for special encodings.

Relevant examples:
 - [Keycloak operator](https://github.com/keycloak/keycloak/pull/10098/files)
 - [Akka operator](https://github.com/lightbend/akka-operator-helm/blob/d1859063405381e96b082288241797963e67d4fd/akka-operator/crds/v1/akka-microservices-crd.yml#L385-L388)
 - [Flink CLI](https://nightlies.apache.org/flink/flink-docs-release-1.13/docs/deployment/config/#kubernetes-pod-template-file)
 - [Spark CLI](https://spark.apache.org/docs/latest/running-on-kubernetes.html#pod-template)

__PROS:__
- covers all the known use-cases and more

__CONS:__
- inexperienced users might accidentally compromise functionalities of the operator
- hard if not impossible to predict how all the fields will interact with the default options
- confusion as there are already a few options encoded in the top level of the CRD

**Mitigation**

A clear documentation regarding this feature and/or a strong advice to use it only after proper testing might help.

**Technical implementation notes**

_Additional challenge_

The implementation of `podTemplate` cannot be easily done automatically as there are a few invariants e.g.:

- when defining property on the container 0 we need to override container 0 fields
- when defining extra containers they should be appended
- when defining commands/args etc. the entire list should be substituted

Experience proves that a careful first implementation of this feature rarely requires complex maintenance.

**Comment by jsenko** [comment]
Resolved by #212
