### ISSUE TITLE
Allow setting of ksink

### ISSUE THREAD

**Issue by mathianasj** [Apicurio/apicurio-registry-operator#185]
I would like to be able to set the K_SINK environment variable to enable the ability to publish cloud events when changes to the schema artifacts occur.  This will solve being able to trigger pipelines for instance to rebuild dependent services and perform automated integration testing to simplify the workflow for developers.

I am going to attempt a pull request using existing patterns for setting of env variables

**Comment by jsenko** [comment]
This issue has been resolved, closing.
