### ISSUE TITLE
Please add support for Kubernetes 1.25+

### ISSUE THREAD

**Issue by valencetech** [Apicurio/apicurio-registry-operator#199]
The Apicurio Restristry CRD deploys a Pod Distruption Budget resource using a deprecated API.
PDB API policy/vibeta1 is no longer supported and this causing the apicurio-registry-operator pod to fail to start.

**Comment by jsenko** [comment]
hi @valencetech this issue is resolved in the dev version (in the `main` branch), so it should be just a matter of releasing a new version into Operator Hub. I plan to do that soon.

**Comment by pelikanmartin** [comment]
Hi @jsenko, any timeline on releasing new version compatible with Kubernetes 1.25? We just upgraded to 1.25 and found out APICurio Registry Operator is broken.

**Comment by jeacott1** [comment]
1.25 active support ends 28 May 2023 - that's not long to get this fixed.

**Comment by grigoni** [comment]
hello
policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+ 
we need to migrate from 1.4 to 1.25 soon, this is a problem for the stage planning
thx

**Comment by airen29** [comment]
Hello.
 Any information of the timeline related to releasing new version compatible with Kubernetes 1.25?

Thank you very much.

**Comment by michael4screen** [comment]
Hi @jsenko,
Is there a timeline for releasing the new version ?
Thank you !

**Comment by jsenko** [comment]
hi, sorry for waiting, I've been busy with other work recently. I plan to do the Operator Hub release ASAP after we're done with work on Service Registry release.

**Comment by PipeFTW** [comment]
Hi @jsenko,

any updates on this?

**Comment by jsenko** [comment]
Done https://github.com/Apicurio/apicurio-registry-operator/releases/tag/v1.1.0-v2.4.12.final
