### ISSUE TITLE
Documentation for Keycloak configuration + Apicurio Registry is outdated

### ISSUE THREAD

**Issue by oscerd** [Apicurio/apicurio-registry-operator#238]
https://www.apicur.io/registry/docs/apicurio-registry-operator/1.1.0-v2.4.12.final/assembly-registry-maintenance.html

With the latest versions of Keycloak operator this documentation is not working anymore

**Comment by jsenko** [comment]
Note: Consider using or mentioning examples of using Ansible for deploying/configuring Keycloak https://github.com/ansible-middleware/keycloak

**Comment by carlesarnal** [comment]
This has been partially addressed by fixing the [docker-compose distro](https://github.com/Apicurio/apicurio-registry/tree/main/distro/docker-compose).

**Comment by jsenko** [comment]
Fixed by https://github.com/Apicurio/apicurio-registry-operator/pull/239
