### ISSUE TITLE
Security based on SCRAM for kafka backend should also consider plain listener

### ISSUE THREAD

**Issue by rgordill** [Apicurio/apicurio-registry-operator#32]
Currently, the operator needs trustStoreSecretName to connect using tls. 

However, kafka can be configured also with plain connection, but using SCRAM for authentication/authorization. The operator should consider ssl in scram security as optional.

**Comment by didentifier** [comment]
Can I mount the secrets from strimzi user secret? Also is there only support for trustore, do I not need a keystore?

**Comment by rgordill** [comment]
As latest version is jumped to 2.x, it makes no sense this issue anymore.

**Comment by amruthpremjith** [comment]
Would it be possible to use scram with plain listeners now, could you please provide some kind of documentation for it? I am currently running a strimzi kafka with scram-sha-512 authentication on plain listeners and was thinking of using it for apicurio also.
