### ISSUE TITLE
Nothing happens when ApicurioRegistry CR is deleted

### ISSUE THREAD

**Issue by abkieling** [Apicurio/apicurio-registry-operator#43]
The operator isn't undeploying Apicurio Registry when the ApicurioRegistry CR is deleted.

**Comment by redhatHameed** [comment]
@jsenko  Can't reproduce this issue :  

Steps 1 : 

`operator-sdk up local`

Step2 : 

 `oc create -f docs/resources/example-cr/in-memory-with-image.yaml`
wait for sucessfull creation of pods

Step:3 

`oc delete -f docs/resources/example-cr/in-memory-with-image.yaml`

Observe that, pods and deployment get deleted.
