### ISSUE TITLE
build.sh deploys operator and operand in incorrect namespace

### ISSUE THREAD

**Issue by akieling** [Apicurio/apicurio-registry-operator#51]
The following command installs the operator and operand in the current namespace, not in the one specified in the command:

```
./build.sh mkdeploy -r "quay.io/akieling" -n apicurio-registry
```

**Comment by jsenko** [comment]
Should be fixed by https://github.com/Apicurio/apicurio-registry-operator/pull/68 (updating build.sh mkdeploy and mkundeploy functions).
