### ISSUE TITLE
UT000068: Servlet path match failed

### ISSUE THREAD

**Issue by didentifier** [Apicurio/apicurio-registry-operator#55]
I keep getting the following error message when I try to save my schemas from Lenses.io

`2020-07-20 12:56:50,888 ERROR [io.und.request] (executor-thread-11) UT005071: Undertow request failed HttpServerExchange{ POST http://apicurioregistry.lagom.apps.marlow.naboocore.com/subjects/f/versions delegate io.undertow.vertx.VertxHttpExchange@63090394}: java.lang.IllegalArgumentException: UT000068: Servlet path match failed`

Can someone help me with that?

**Comment by jsenko** [comment]
Hi, the correct path to the Confluent compat. API is `http://apicurioregistry.lagom.apps.marlow.naboocore.com/api/ccompat/subjects/f/versions` . Please let us know more details about how to reproduce your issue if needed.

**Comment by jsenko** [comment]
Closing the issue, create a new one please if you still get the error
