### ISSUE TITLE
make it possible to configure requests&limits for cpu&memory for registry pod in ApicurioRegistry CR

### ISSUE THREAD

**Issue by jhutar** [Apicurio/apicurio-registry-operator#79]
This might be useful when you need to give more memory to the registry due to higher load on the service

**Comment by jsenko** [comment]
Note - examples from Strimzi:
https://strimzi.io/docs/operators/latest/using.html#ref-resource-limits-and-requests-deployment-configuration-kafka
https://strimzi.io/docs/operators/latest/using.html#ref-jvm-options-deployment-configuration-kafka

**Comment by jsenko** [comment]
Resolved by #212
