### ISSUE TITLE
Multiple deploymentconfig and pods randomly created

### ISSUE THREAD

**Issue by makandre** [Apicurio/apicurio-registry-operator#89]
I'm trying out `0.0.3-v1.2.3.final` of the operator, using built-in `infinispan` storage

After the registry is up for some time, something (I have not isolated what triggers this) causes multiple `DeploymentConfigs` resources to be created, which leads to multiple pods getting spun up.  The new pods do not have the schemas that I have in my registry originally, and requests to fetch the schemas fail.

**Comment by jsenko** [comment]
hi, thanks for reporting this issue. Do you have logs available from the time this happens?

**Comment by makandre** [comment]
Let me try to collect some the next time it happens

**Comment by makandre** [comment]
[apicurio-operator.log](https://github.com/Apicurio/apicurio-registry-operator/files/5501747/apicurio-operator.log)

**Comment by jsenko** [comment]
This issue has been resolved, and should not affect the upcoming `1.0.0-v2.0.0.final` release. Please create a new issue if the problem still occurs or if you need this fixed for `0.x` versions.
