### ISSUE TITLE
Overall operator issues

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry-operator#93]
as discussed, here is a list of overall operator issues that we currently identified:

* do not explicitly cleanup resources and use ownerReferences to do so, and verify it works
* ocp route creation algorithm could be improved, there are situations where there is a noticeable delay for the route to be created. Route creation algorithm should be simplified and leverage default route host value when possible.
* operator creates too many watches, the issue is in `cf_service_monitor` .  But watches should be only created once at operator start up, this will need refactor in current control functions implementation
* internal dependency management, there is a map to hold business logic services for each registry CR, this should be improved/refactored and try to get rid of that map
* reconcile loop gets executed too many times, this should be improved fixing the watches leak and filtering events using [predicates](https://github.com/apache/camel-k/blob/master/pkg/controller/integration/integration_controller.go#L80)

**Comment by jsenko** [comment]
This issue has been resolved, and will not affect the upcoming `1.0.0-v2.0.0.final` release.
