### ISSUE TITLE
Implement SQL persistence type

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry-operator#94]
SQL will be similar to JPA, env vars are the same, it just changes the container image name

I guess we are dropping the JPA option and adding the SQL new one.

If we drop the JPA option the operator will start to log various errors if it encounters JPA deployments... but we should be ok, I think operator won't remove anything.

We will have to document this or implement some upgrade logic to migrate from JPA deployments to SQL ones. Because of tech-preview, I think just warning JPA persistence is discontinued will be ok

@Apicurio/developers thoughts?

**Comment by jsenko** [comment]
This issue has been resolved, and will not affect the upcoming `1.0.0-v2.0.0.final` release.
